name: sync list to gitee

on:
  schedule:
    - cron: "18 13 */6 * *"
  push:
    branches: 
      - 'master'
    paths: 
      - 'anti-ad-*.txt'
      - 'anti-ad-*.conf'
      - 'adblock-for-dnsmasq.conf'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone the gitee
      run: git clone https://gitee.com/privacy-protection-tools/anti-ad.git ~/gitee
    - name: copy some list files
      run: |
        echo "https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_PASS }}@gitee.com">~/.git-credentials
        cp ./anti-ad-easylist.txt ~/gitee/easylist.txt
        cp ./adblock-for-dnsmasq.conf ~/gitee/dnsmasq.conf
        cp ./adblock-for-dnsmasq.conf ~/gitee/anti-ad-for-dnsmasq.conf
        cp ./anti-ad-smartdns.conf ~/gitee/anti-ad-for-smartdns.conf
        cp ./anti-ad-surge.txt ~/gitee/surge.txt
        cp ./anti-ad-domains.txt ~/gitee/domains.txt
    - name: Commit files
      run: |
        cd ~/gitee
        git config --global credential.helper store
        git config --local user.email "${{ secrets.GITEE_EMAIL }}"
        git config --local user.name "gently"
        git add .
        git commit -m "pull newest list." -a
        git push -u origin master
